### ISSUE TITLE
Venom build fails

### ISSUE THREAD

**Issue by MageSlayer** [zetok/gentoo-overlay-tox#17]
Hi

I am on Gentoo x86. 
Trying to install Venom results in following error:

-- Check for working C compiler: /usr/lib/ccache/bin/i686-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/lib/ccache/bin/i686-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found Vala: /usr/bin/valac-0.22 (found version "0.22.1") 
Venom version 0.2.0
32 bit architecture detected.
-- Found Vala: /usr/bin/valac-0.22 (found suitable version "0.22.1", minimum required is "0.18.1") 
-- Found PkgConfig: /usr/bin/i686-pc-linux-gnu-pkg-config (found version "0.28") 
-- checking for module 'gtk+-3.0>=3.4'
--   package 'gtk+-3.0>=3.4' not found
-- checking for module 'gio-2.0>=2.32'
--   found gio-2.0, version 2.40.0
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:284 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:338 (_pkg_check_modules_internal)
  cmake/PkgCheckModulesFullpath.cmake:21 (PKG_CHECK_MODULES)
  src/CMakeLists.txt:31 (PKG_CHECK_MODULES_FULLPATH)

-- checking for module 'glib-2.0>=2.32'
--   found glib-2.0, version 2.40.0
-- checking for module 'sqlite3>=3.7'
--   found sqlite3, version 3.7.15.2
-- checking for module 'json-glib-1.0>=0.14'
--   found json-glib-1.0, version 0.16.2
-- checking for module 'libtoxcore>=0.0'
--   found libtoxcore, version 0.0.0
Optional features / dependencies:
   [ ] ENABLE_DJBDNS - resolve tox dns ids using djbdns (required for glib <= 2.32)
   [ ] ENABLE_QR_ENCODE - show QR codes (requires libqrencode)

Error:
- In program cave perform install --hooks --managed-output --output-exclusivity with-others =net-im/venom-9999:0::gentoo-overlay-tox --destination installed --x-of-y 1 of 1:
- When installing 'net-im/venom-9999:0::gentoo-overlay-tox':
- When running an ebuild command on 'net-im/venom-9999:0::gentoo-overlay-tox':
- Install failed for 'net-im/venom-9999:0::gentoo-overlay-tox' (paludis::ActionFailedError)

-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -O2 -march=i686 -pipe 
C++  
Linker flags:
Executable       -Wl,--as-needed
Module           -Wl,--as-needed
Shared           -Wl,--as-needed

-- Configuring incomplete, errors occurred!

**Comment by urras** [comment]
> -- package 'gtk+-3.0>=3.4' not found

That doesn't look right
Is 'x11-libs/gtk+' installed?

**Comment by MageSlayer** [comment]
Aha!
- x11-libs/gtk+
  ::gentoo                  1.2.10-r12 {:1} 2.24.23 (2.24.23-r2)K {:2} 3.4.4 3.10.8\* (3.12.2)K {:3}
  ::installed               1.2.10-r12 {:1} 2.24.20 {:2} 3.2.3 {:3}

After I manually updated gtk+ it builds successfully now.

But seriously, guys, why don't you state required versions explicitly in the ebuild?
I mean not all Gentoo users are rebuilding world continuously.

**Comment by holgersson32644** [comment]
Seriously, guy, how should we expect that someone uses such old software that's not even in the main tree anymore? ;)

I added the explizit depency for gtk >= gtk 3.4 anyway & close that issue.

**Comment by MageSlayer** [comment]
Thanks :)
