### ISSUE TITLE
Add the overlay to the layman list

### ISSUE THREAD

**Issue by lehitoskin** [zetok/gentoo-overlay-tox#21]
Have you checked out https://git.overlays.gentoo.org/ yet? I think that might be the way you add the overlay to the layman list.

**Comment by urras** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=515900
Sure hope I did this right

**Comment by hasufell** [comment]
Why not contribute to gentoo instead? I wrote some ebuilds for this some months back, but back then it wasn't in usable shape.

**Comment by urras** [comment]
The overlay has been added to the official layman list
https://bugs.gentoo.org/show_bug.cgi?id=515900#c2
