### ISSUE TITLE
Repository 'gentoo-overlay-tox' is implicitly using 'portage-1' profile format in its profiles/package.mask, but the repository profiles are not marked as that format

### ISSUE THREAD

**Issue by CrazyCrab** [zetok/gentoo-overlay-tox#23]
This is a warning emerge gives me. It's something that should be fixed on your side, right?

/usr/lib64/portage/pym/portage/package/ebuild/_config/MaskManager.py:50: UserWarning: Repository 'gentoo-overlay-tox' is implicitly using 'portage-1' profile format in its profiles/package.mask, but the repository profiles are not marked as that format.  This will break in the future.  Please either convert the following paths to files, or add
profile-formats = portage-1
to the repository's layout.conf.

**Comment by holgersson32644** [comment]
It's already fixed in commit c351ea3565d73cba6dfd8509fde3c20fd21f568c. Thanks for the hint.
