### ISSUE TITLE
package.mask as a directory violates the PMS

### ISSUE THREAD

**Issue by l29ah** [zetok/gentoo-overlay-tox#25]
...and makes this overlay incompatible with alternative PMS implementations (notably, paludis).

**Comment by holgersson32644** [comment]
Thanks for the hint. To be honest I didn't knew that PMS[1](a link would have been nice BTW ;-));
obviously I violated it with splitting the package.mask.
But to explain my chain of thought: I use portage at gentoo, and portage itself works very well with files and directories containing files. All complainment portage gave is quoted in #23; in my eyes it was no problem to add that informative line in the layout.conf and being done.
Maybe portage should give an comment that leads directly to the PMS (or IMHO even better) the PMS should be extented to directories. Anyway, the place to discuss that isn't here, and until the PMS changes, only files will be used.

regards,
holgersson

[1] http://wiki.gentoo.org/wiki/Project:PMS
