### ISSUE TITLE
Remove venom hard mask

### ISSUE THREAD

**Issue by infirit** [zetok/gentoo-overlay-tox#26]
I fixed the problem with venom not building on gentoo in https://github.com/naxuroqa/Venom/pull/213. So either wait for that to be merged or add it as a patch.

**Comment by holgersson32644** [comment]
Thank you! We'll wait and unmask then.

**Comment by infirit** [comment]
Merged, https://github.com/naxuroqa/Venom/commit/92ae06d6ca8908af65389a67062649e3f490ce67

**Comment by holgersson32644** [comment]
Hard masked removed, thanks for notification.
