### ISSUE TITLE
Utox ebuild is broken

### ISSUE THREAD

**Issue by sonOfRa** [zetok/gentoo-overlay-tox#41]
Utox is installed to /usr/usr/local/bin/utox. This is very wrong. Additional 'usr' is wrong, and packages installed by portage should not go to /usr/local/, but into /usr/, even when installed through layman.

**Comment by urras** [comment]
Alright, want me to revert cf874cc?

**Comment by urras** [comment]
Actually, for me and @zetok, it installs to /usr/bin/utox with the current ebuild. Maybe unmerge and re-emerge?

**Comment by sonOfRa** [comment]
Sorry this took so long. Works now, for whatever reason
