### ISSUE TITLE
venom(-av) wrongly requires GCC 4.8.0

### ISSUE THREAD

**Issue by TheLastProject** [zetok/gentoo-overlay-tox#48]
The venom and venom-av ebuilds require GCC 4.8.0, but they don't actually need it. GCC 4.8.0 is still marked as unstable in Gentoo. The latest stable version, 4.7.3, works just fine. Please lower the requirement to at very least the latest stable version, preferably to the lowest version necessary.

**Comment by zetok** [comment]
@hasufell is there any reason why venom would require high gcc version?

**Comment by hasufell** [comment]
I guess that sneaked in.

**Comment by zetok** [comment]
Fixed.
