### ISSUE TITLE
net-im/venom-9999 Fails to compile:  too few arguments to function ‘tox_join_groupchat’

### ISSUE THREAD

**Issue by kwhat** [zetok/gentoo-overlay-tox#53]
Looks like the venom trunk is not building properly and I am not sure if its an ebuild issue or if I should report this upstream.  Full build log: https://bpaste.net/show/25794b2cc8fe  Emerge Info: https://bpaste.net/show/2068bf56ce41  (Sorry for pastebin but no attachment support on github)  Looks like the issue has been reported upstream: https://github.com/naxuroqa/Venom/issues/267

```
/var/tmp/portage/net-im/venom-9999/work/venom-9999_build/src/core/ToxSession.c: In function ‘venom_tox_session_join_groupchat’:
/var/tmp/portage/net-im/venom-9999/work/venom-9999_build/src/core/ToxSession.c:3222:4: error: too few arguments to function ‘tox_join_groupchat’
_tmp10_ = tox_join_groupchat (_tmp3_, (gint32) _tmp6_, _tmp9_);
```

**Comment by zetok** [comment]
There was a change to core that broke compatibility, Venom has yet to be compatible with newest core.

Unless reproducible after upstream issue you've linked to has been resolved, it's a Venom bug.
