### ISSUE TITLE
Add the gTox client to this overlay

### ISSUE THREAD

**Issue by eternal-sorrow** [zetok/gentoo-overlay-tox#80]
https://github.com/KoKuToru/gTox

**Comment by lehitoskin** [comment]
Right now it's mostly done, just need to wait on gtox to remove submodule dependencies so it'll build properly.

**Comment by KoKuToru** [comment]
gtox is updated now, doesn't need submodules now.
but dependencies and folder structure changed !

**Comment by lehitoskin** [comment]
What is the flatbuffers dependency? Is it [this?](https://github.com/google/flatbuffers)

**Comment by KoKuToru** [comment]
yes

**Comment by lehitoskin** [comment]
@KoKuToru It seems gtox currently doesn't compile. Here's my build log and the error I'm getting: https://bpaste.net/show/8733132768eb

**Comment by KoKuToru** [comment]
yeah too old compiler.. no c++14 support.. I will check if I can remove it ?

**Comment by lehitoskin** [comment]
That's up to you, but gcc version 4.8.4 is the latest stable release in Gentoo. The others are listed as unstable.

**Comment by KoKuToru** [comment]
Is there are a problem with using a newer gcc ?
I would prefer to not downgrade to C++11

**Comment by lehitoskin** [comment]
What version are you using to build gtox? It still fails on version 4.9.3.

```
[ 74%] Building CXX object CMakeFiles/gTox.dir/widget/avatar.cpp.o
[ 76%] Building CXX object CMakeFiles/gTox.dir/widget/contact.cpp.o
In file included from /usr/include/gtkmm-3.0/gtkmm/action.h:32:0,
                 from /usr/include/gtkmm-3.0/gtkmm/toggleaction.h:28,
                 from /usr/include/gtkmm-3.0/gtkmm.h:95,
                 from /home/lehi/Downloads/gtox/src/widget/contact.h:23,
                 from /home/lehi/Downloads/gtox/src/widget/contact.cpp:20:
/usr/include/gtkmm-3.0/gtkmm/widget.h: In lambda function:
/usr/include/gtkmm-3.0/gtkmm/widget.h:380:16: error: ‘virtual void Gtk::Widget::on_hide()’ is protected
   virtual void on_hide();
                ^
/home/lehi/Downloads/gtox/src/widget/contact.cpp:275:42: error: within this context
                     Gtk::Widget::on_hide();
                                          ^
CMakeFiles/gTox.dir/build.make:284: recipe for target 'CMakeFiles/gTox.dir/widget/contact.cpp.o' failed
make[2]: *** [CMakeFiles/gTox.dir/widget/contact.cpp.o] Error 1
CMakeFiles/Makefile2:66: recipe for target 'CMakeFiles/gTox.dir/all' failed
make[1]: *** [CMakeFiles/gTox.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

P.S. gcc versions 5.X are all masked. You really shouldn't expect Gentoo users to try and install 5.X until it becomes unmasked.

**Comment by zetok** [comment]
@lehitoskin IIRC gcc 5 has C++14

**Comment by KoKuToru** [comment]
Looks like 4.9.3 has problems with access protected-members from a lambda ..? That should be a C++11 feature..
So even if I would downgrade to C++11 it won't work ..

**Comment by lehitoskin** [comment]
All right. 5.1.0 it is.

**Comment by KoKuToru** [comment]
Will work with older gcc/g++ now (tested with 4.9.3)

**Comment by lehitoskin** [comment]
Added gtox to overlay via 94de63b534a3b4ab5305abe6010db751478e0dcb
