### ISSUE TITLE
net-im/tox-prpl-9999 with the latest net-libs/tox: src/toxprpl.c:264:57: error: unknown type name ‘TOX_USERSTATUS’

### ISSUE THREAD

**Issue by bircoph** [zetok/gentoo-overlay-tox#83]
Hi,

tox-prpl fails to build with the latest net-libs/tox (updated today).
build.log: https://bpaste.net/show/ec027a354f58
environment: https://bpaste.net/show/096b99955ca3
emerge --info: https://bpaste.net/show/ecec9dd5a084

**Comment by lehitoskin** [comment]
I don't know if tox-prpl is even still maintained. It's possible it's using a very, very old API.

**Comment by zetok** [comment]
that's an issue with `tox-prpl`

**Comment by bircoph** [comment]
Since this package is maintained in tox-overlay, I reported issue here.
Do you propose to report it to upstream?

**Comment by lehitoskin** [comment]
@bircoph Yes, I suspect tox-prpl is woefully out of date and there's nothing we can do about it from here. Of course, we could also just remove the package as well.

**Comment by urras** [comment]
@lehitoskin If @jin-eld no longer wishes to maintain tox-prpl, I'd recommend removing it entirely from the repo. It's what we did with Venom and the old Qt client in the past

**Comment by zetok** [comment]
Looks like it has come to it.
