### ISSUE TITLE
WHY

### ISSUE THREAD

**Issue by urras** [zetok/gentoo-overlay-tox#87]
@zetok,
Why did you remove the repo from the Tox org?

**Comment by zetok** [comment]
I'm maintaining it - people in charge of `Tox` org on github has been doing some weird (so to say) stuff, and I've transferred repo to me, to keep ability to maintain it.

Note that this movement is ~consistent with what has been going on with
other repos as well - e.g. Toxic has been transferred to JFreegman.

I've tried to contact you earlier - you might want to check your gmail `:)`

**Comment by urras** [comment]
Ah, understood. I sent you an email from my new address; if you need anything just shoot me an email.

**Comment by zetok** [comment]
Hmm, that's weird - I don't see any new messages from you in my inbox (there's nothing new in spam too) - did you send the message to zetok@openmailbox.org ?

**Comment by urras** [comment]
No, I sent it to the email in the AUTHORS file - the Gmail one. I'll send it to your other one in a bit

**Comment by zetok** [comment]
Yeah, I also don't see anything from you on gmail `:(` - are you sure that your mail server is configured properly?
