### ISSUE TITLE
utox: xlib/main.c:199:35: error: 'TRUE' undeclared (first use in this function)

### ISSUE THREAD

**Issue by tot-to** [zetok/gentoo-overlay-tox#90]
layman -s tox-overlay; USE="filter_audio -dbus" emerge utox
fails with the error:
utox: xlib/main.c:199:35: error: 'TRUE' undeclared (first use in this function)

I've tried to reinstall all dependencies (freetype libfilteraudio libv4l libvpx openal libX11 libXext), but I does don change anything.

See build.log attached.

**Comment by lehitoskin** [comment]
Could you try compiling utox outside portage?

**Comment by tot-to** [comment]
Ok, here is what I did and the result:
git clone git://github.com/GrayHatter/uTox.git
cd uTox
vim Makefile # change "DBUS = 1" to "DBUS = 0"
make all
  CC    tooltip.o
  CC    avatar.o
  CC    theme.o
  CC    friend.o
  CC    button.o
  CC    video.o
  CC    commands.o
  CC    scrollable.o
  CC    dropdown.o
  CC    ui.o
  CC    contextmenu.o
  CC    list.o
  CC    dns.o
  CC    groups.o
  CC    audio.o
  CC    edit.o
  CC    ui_dropdown.o
  CC    main.o
In file included from xlib/main.c:102:0,
                 from main.c:15:
xlib/freetype.c: In function 'font_getglyph':
xlib/freetype.c:189:5: warning: implicit declaration of function 'FT_Library_SetLcdFilter' [-Wimplicit-function-declaration]
     FT_Library_SetLcdFilter( ftlib, lcd_filter);
     ^
In file included from main.c:15:0:
xlib/main.c: In function 'init_ptt':
xlib/main.c:199:35: error: 'TRUE' undeclared (first use in this function)
         XSynchronize(ptt_display, TRUE);
                                   ^
xlib/main.c:199:35: note: each undeclared identifier is reported only once for each function it appears in
Makefile:112: recipe for target 'main.o' failed
make: **\* [main.o] Error 1

**Comment by lehitoskin** [comment]
This is a problem with Utox, not the overlay. Go and make an issue there instead.

**Comment by zetok** [comment]
Closing, since upstream issue was closed.
